name: Publish — Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout kode
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Log ind på GHCR
      - name: Log in to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Byg og push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ijm-labs/dreamscope-frontend:latest
            ghcr.io/ijm-labs/dreamscope-frontend:${{ github.sha }}
